name: TamizajESE
description: A new Flutter project.
publish_to: 'Herramienta para tamizaje de riesgo cardiovascular de la Red de Salud de Oriente'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dependencias de UI y Navegación
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  # 'intl' es necesaria para el formato de fechas (DateFormat) usado en la generación de datos.
  intl: ^0.20.2
  json_path: ^0.7.1
  page_transition: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  fl_chart: ^0.68.0

  # Dependencias de nuestra arquitectura
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  # --- AÑADIDO ---
  # Se agrega Faker para la generación de datos de prueba aleatorios.
  faker: ^2.2.0
  csv: ^6.0.0
  archive: ^4.0.7
  share_plus: ^11.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # o la versión que tengas

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# ==========================================================
# SECCIÓN CORREGIDA
# ==========================================================
flutter:
  uses-material-design: true
  assets:
    # Añadimos la ruta a la carpeta de íconos para que sea accesible
    - assets/icon/
    - assets/sqlite_db_files/