# Propiedades para la firma de la App (¡NO SUBIR A GIT!)
storePassword=900526
keyPassword=900526
keyAlias=TamizajEse
storeFile=/Users/ncardona90/Library/Mobile Documents/com~apple~CloudDocs/ESE Oriente/Ejecucion/Producto/Desarrollo/APK/Tamizajes4/android/app/TamizajEse.jks